### ISSUE TITLE
Only need to show yesterday, today and tomorrow shows in single scroll without any Filters of days.

### ISSUE THREAD

**Issue by arunoodles** [egeniq/android-tv-program-guide#24]
Hi, 

I hope you are doing well,

I'm using your EPG library but facing a problem in getting yesterday's data. I just commented on the filter part (setup filters method) because that is not needed in my project. I need only three days yesterday, today, and tomorrow data for programs with single scrolling only but unable to find the where to make a change in the program guide fragment. Can you please help me to resolve this?

**Comment by dzolnai** [comment]
Hi Arun,

Attached you can find the patch file which changes the demo to do what you want.
Basically it does 3 things:

1. Hide the filters for day and time of day
2. Changes the manager that the cutoff time is extended +1 day in both directions
3. Changes the demo data so that it is filled for one extra day in both directions.

Hope that helps.

[3days-patch.txt](https://github.com/egeniq/android-tv-program-guide/files/5634206/3days-patch.txt)

**Comment by arunoodles** [comment]
Hi Dzolnai,

Thanks for your support. It worked for me.
