### ISSUE TITLE
Timeline doesn't match schedule start time

### ISSUE THREAD

**Issue by ybonnetain** [egeniq/android-tv-program-guide#48]
Hello,
In the demo project the schedule items that we layout in a row does not correspond to the information displayed in the timeline.

<img width="1229" alt="Screenshot 2023-01-30 at 12 29 13" src="https://user-images.githubusercontent.com/11773957/215465814-d19e7eee-4cae-4f80-983b-04486be02ccc.png">

My system is configured on UTC +1
I supposed I might be missing something maybe ?

**Comment by dzolnai** [comment]
Hello, maybe you could push your version to a branch where I can investigate? The timezone itself shouldn't be an issue.

Cheers,
Daniel

**Comment by ybonnetain** [comment]
I just identified that it is something about the styling I have done somehow.
I wouldn't want to waste your time with that :)
However I would like to ask you something:
How would you go about implementing lazy data loading in the grid for both channels and past/future schedules ?

**Comment by dzolnai** [comment]
> How would you go about implementing lazy data loading in the grid for both channels and past/future schedules ?

That's quite complicated, because the grid only refreshes all the data at once.
You can keep what you have already loaded in the memory, then extend with what you have just fetched, and then just refresh with what you have loaded.
You could try refreshing by not showing a loader, but instantly putting the data in the recyclerview. If the scroll position is kept, it might work fine, I never tried that.

**Comment by ybonnetain** [comment]
Yes I have tried it and the scroll position is kept which is good.
The focus finder triggers and move the selection away but no big deal.
I am just afraid I might end up with a huge dataset as we have A LOT of broadcasters :/

**Comment by dzolnai** [comment]
In that case I would try extending the sample project with more example data (e.g. create some more broadcasters in a for loop) and check how the grid would behave. Vertically it shouldn't be an issue since we are speaking about a RecyclerView so only the rows are drawn which are on the screen. Horizontal would be questionable since it is a RecyclerView in a RecyclerView, but since you are constrained there with the 24 hours, I think that would be okay too.

**Comment by ybonnetain** [comment]
Hi, sorry to bother again.
I am really struggling to make the timeline roll over several days.
I wonder if it's even possible ?

**Comment by dzolnai** [comment]
Interesting question :)
I've edited the demo that it displays 7 days of data instead of just 1. It works fine with my changes.
Except that the day selector doesn't change based on the current position, although that can be easily fixed, just follow the code for the 'time of the day' selector.
Here you can find the diff: [7daysdemo.txt](https://github.com/egeniq/android-tv-program-guide/files/10547741/7daysdemo.txt)

**Comment by ybonnetain** [comment]
> 

🙏 of course. Thanks a lot
