### ISSUE TITLE
Channel Image Focusable

### ISSUE THREAD

**Issue by JpouHG** [egeniq/android-tv-program-guide#56]
Hello, 

I wanted to ask if it is possible to make the channel image focusable. What i want is to make channel detail more accesible, so when i go all way left, access the channel by clicking the image.

Thanks, 
Joaquín.

**Comment by jleahy2** [comment]
I would like to know how this is done too.

**Comment by dzolnai** [comment]
First of all, thanks for your patience!
I have added this feature to the library, which is turned off by default for backwards compatibility (although it is enabled in the demo for showcase purposes).
You can enable this by overriding `CAN_FOCUS_CHANNEL` to `true` in your implementation of `ProgramGuideFragment`.
I am closing this issue since it is resolved now, but feel free to reopen if you have concerns or problems with this new feature.
